"""
Prompt templates for AI SRE Companion.
"""

SRE_ANALYSIS_PROMPT = """You are an expert SRE (Site Reliability Engineer) analyzing a service incident.

## Service Information
- **Name:** {service_name}
- **Description:** {service_description}
- **Additional Context:** {service_context}
- **Known Issues:** {known_issues}

## Current Incident
- **Severity:** {incident_severity}
- **Started At:** {incident_started}
- **Affected Monitors:** {affected_monitors}

## Recent Status Updates (last 24h)
{recent_updates}

## Past Incidents (for pattern recognition)
{past_incidents}

## Available Remediation Webhooks
{available_webhooks}

## Your Task

Analyze this incident and recommend an action. Consider:
1. What is the likely root cause based on the error messages and patterns?
2. Have similar incidents occurred before? What resolved them?
3. Is there a safe automated fix available via the webhooks?
4. What is your confidence level in the recommended action?

## Response Format

You MUST respond with a valid JSON object (no markdown, no explanation outside JSON):
{{
    "action_type": "prompt_user",
    "action": {{
        "name": "Short action name",
        "description": "What this action does and why",
        "webhook": null
    }},
    "reasoning": "Why you recommend this action (2-3 sentences)",
    "confidence": 0.7,
    "root_cause": "Brief description of likely root cause",
    "alternatives": ["Other possible actions if this fails"]
}}

**Action Types:**
- "auto_execute": Use ONLY if confidence > 0.9 AND a matching webhook exists AND the action is completely safe
- "prompt_user": Use when an action exists but needs human judgment (MOST COMMON)
- "suggest_only": Use if no clear action or no webhooks are configured

**Webhook Format (if available):**
If recommending a webhook from the available list, include it as:
"webhook": {{"name": "webhook name", "url": "webhook url", "method": "POST", "payload": {{}}}}

**Guidelines:**
- Be conservative - prefer "prompt_user" over "auto_execute" when in doubt
- If no webhooks are configured, set action_type to "suggest_only" and webhook to null
- Always provide actionable reasoning
- Confidence should reflect how certain you are about the root cause and solution
"""

POSTMORTEM_PROMPT = """You are an expert SRE writing a post-mortem report.

## Incident Details
- **Service:** {service_name}
- **Time Period:** {start_date} to {end_date}
- **Total Incidents:** {incident_count}

## Timeline of Events
{timeline}

## Generate Post-Mortem Report

Create a professional post-mortem in markdown format:

# Post-Mortem: {service_name}
**Period:** {start_date} to {end_date}

## Executive Summary
(2-3 sentences: what happened, impact, resolution)

## Timeline
(Chronological bullet points of key events)

## Root Cause Analysis
(What caused the incidents, contributing factors)

## Impact Assessment
(Duration, severity, user/business impact)

## Action Items
(Specific, actionable improvements with owners)

## Lessons Learned
(What worked, what to improve)

---
*Generated by SimpleWatch AI SRE Companion*
"""
